### PR TITLE
Fix map_error

### LINKED ISSUE #8: Some problems with map_error
1. Currently, `map_error(e)` returns error class or instance of error class for both cases mapped and unmapped.  So we will never get 500 error in `mapped ||= ::JsonapiErrorsHandler::Errors::StandardError.new` in `handle_error(e)`. 

I suggest that we should return `nil` in case the error does not map, so we can achieve the expected behaviour.
2. `constantize` is not understood without Rails, so we should change to something similar but for Ruby like `Object.const_get(string)`

### PR DESCRIPTION
**Pull request by nthngoc277**
Fix #8

### CODE REVIEW

File: lib/jsonapi_errors_handler.rb [hunk 1]
```diff
@@ -16,21 +16,14 @@ def self.included(base)
...
-        end
+        mapped ||= ::JsonapiErrorsHandler::Errors::StandardError.new
+        render_error(mapped)
       end
 
       def map_error(e)
         error_klass = e.class.name
-        return e if ErrorMapper.mapped_error?(error_klass)
-        ErrorMapper.mapped_errors[error_klass]&.constantize&.new
+        return nil if !ErrorMapper.mapped_error?(error_klass)
```
Comment (swilgosz) [inline lib/jsonapi_errors_handler.rb]: You can use `unless` here.
